CREATE TABLE IF NOT EXISTS CATEGORY_ENTITY(
    CATEGORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POSITION_ID BIGINT,
    CATEGORY_NAME VARCHAR(255)
);

INSERT INTO CATEGORY_ENTITY(POSITION_ID, CATEGORY_NAME)
VALUES(1, 'Starters');

INSERT INTO CATEGORY_ENTITY(POSITION_ID, CATEGORY_NAME)
VALUES(2, 'Soups');

INSERT INTO CATEGORY_ENTITY(POSITION_ID, CATEGORY_NAME)
VALUES(3, 'Main Courses');

INSERT INTO CATEGORY_ENTITY(POSITION_ID, CATEGORY_NAME)
VALUES(4, 'Desserts');

INSERT INTO CATEGORY_ENTITY(POSITION_ID, CATEGORY_NAME)
VALUES(5, 'Cocktails');